data_ingestion:
  bucket_name: "titanic1072025916"
  file_name : "titanic.csv"
  train_ratio : 0.85

data_processing:
  selected_features:
    - 'Pclass'
    - 'Sex'
    - 'Age'
    - 'Fare'
    - 'Embarked'
    - 'Familysize' 
    - 'Isalone'
    - 'HasCabin'
    - 'Title'
    - 'Pclass_Fare'
    - 'Age_Fare' 
    - 'Survived'
